"use client";

import type { Itinerary } from "@/types/itinerary";

interface Props {
  itinerary: Itinerary;
}

function formatItineraryText(itinerary: Itinerary): string {
  const lines: string[] = [
    `WANDER — Trip Itinerary`,
    ``,
    `Destination: ${itinerary.destination}`,
    `Duration: ${itinerary.duration_days} day${itinerary.duration_days !== 1 ? "s" : ""}`,
    `Style: ${itinerary.travel_style}`,
    `Budget: ${itinerary.budget_tier}`,
  ];

  if (itinerary.visa_note) {
    lines.push(``, `VISA ADVISORY`, itinerary.visa_note);
  }

  for (const day of itinerary.days) {
    lines.push(``, `${"─".repeat(40)}`, `${day.date_label.toUpperCase()}`);
    for (const slot of day.slots) {
      lines.push(
        ``,
        `[${slot.time_of_day.toUpperCase()}] ${slot.activity_name}`,
        slot.description,
        `→ ${slot.style_fit}`
      );
    }
  }

  lines.push(``, `─`.repeat(40), `Generated by Wander`);
  return lines.join("\n");
}

function printItinerary(itinerary: Itinerary) {
  const text = formatItineraryText(itinerary);
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(`
    <html>
      <head>
        <title>Wander — ${itinerary.destination}</title>
        <style>
          body { font-family: Georgia, serif; max-width: 680px; margin: 40px auto; line-height: 1.7; color: #1e293b; }
          h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
          pre { white-space: pre-wrap; font-family: inherit; font-size: 0.95rem; }
          @media print { body { margin: 20px; } }
        </style>
      </head>
      <body>
        <h1>Wander — ${itinerary.destination}</h1>
        <pre>${text}</pre>
        <script>window.onload = () => { window.print(); }<\/script>
      </body>
    </html>
  `);
  win.document.close();
}

export default function ExportButtons({ itinerary }: Props) {
  async function handleCopy() {
    await navigator.clipboard.writeText(formatItineraryText(itinerary));
    alert("Itinerary copied to clipboard!");
  }

  return (
    <div className="flex gap-3">
      <button
        onClick={handleCopy}
        className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 shadow-sm transition hover:border-slate-400 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-400 focus:ring-offset-2"
      >
        Copy to clipboard
      </button>
      <button
        onClick={() => printItinerary(itinerary)}
        className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 shadow-sm transition hover:border-slate-400 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-slate-400 focus:ring-offset-2"
      >
        Download PDF
      </button>
    </div>
  );
}
